# Generated by Django 5.1 on 2024-09-10 13:33

from django.db import migrations, models

def create_default_rooms(apps, schema_editor):
    Room = apps.get_model('api', 'Room')
    # Check if default rooms already exist
    if not Room.objects.exists():
        Room.objects.create(room_name='Sports')
        Room.objects.create(room_name='Politics')
        Room.objects.create(room_name='Business')
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_morerooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(create_default_rooms),
    ]
