version: '3.9'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  apiv3:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "5000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: myproject.settings  # Set this to your actual Django settings module
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:

  
# version: '3'

# services:
#   django_dev:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8001
#     ports:
#       - "8001:8001"

#   django_prod:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8002
#     ports:
#       - "8002:8002"