version: '3.9'

services:
  apiv4:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8002:8000"

  # web2:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8001:8000"
    # depends_on:
    #   - db

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: django_db
#       POSTGRES_USER: django_user
#       POSTGRES_PASSWORD: password
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
