# Dockerfile

# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set environment variables to avoid unwanted prompts
ENV PYTHONUNBUFFERED=1

# Set the working directory inside the container
WORKDIR /app2

# Add project metadata
LABEL maintainer="Rafiur <rafiur.267@gmail.com>"
LABEL project="Owo Project"
LABEL version="1.0.0"
# Copy the requirements file into the container at /app
COPY requirements.txt /app2/

# Install the dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app2/

# Expose port 8000 for the Django app
EXPOSE 8000

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
