name: Deploy Django Project to DigitalOcean

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest version of the code from the GitHub repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up SSH for deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy to DigitalOcean Droplet
    - name: Deploy to DigitalOcean
      run: |
        ssh root@your_droplet_ip <<EOF
          cd ${{ secrets.WORK_DIR }}
          git pull origin ${{ secrets.MAIN_BRANCH }}
          python -m venv myprojectenv
        EOF
