name: Deploy Django Project to DigitalOcean

on:
  push:
    branches:
      - api_chatting  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest version of the code from the GitHub repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set up SSH for deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    # Step 3: Deploy to DigitalOcean Droplet
    - name: Deploy to DigitalOcean
      run: |
        ssh root@159.223.119.17 <<EOF
          mkdir myproject
          cd myproject
          git clone https://github.com/arcbsr/Django-api.git
          cd /Django-api/myproject
          git pull origin main
          source /path/to/your/venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
