name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to the droplet
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Create a temporary file for the SSH private key
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Execute remote commands using SSH
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            echo "Navigating to /path/to/Django-api"
            cd /path/to/Django-api

            echo "Checking out the api_chatting branch"
            git checkout api_chatting

            echo "Pulling the latest changes from the api_chatting branch"
            git pull

            echo "Repository successfully updated on the droplet"
          EOF
          
          # Clean up the temporary SSH private key file
          rm private_key.pem
        shell: /usr/bin/bash -e {0}
