name: Django CI Pipeline

on:
  push:
    branches:
      - main  # Runs the pipeline when changes are pushed to the `main` branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the `main` branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the Python version that suits your project

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set up the Django environment variables
      - name: Set up environment
        run: |
          echo "SECRET_KEY=mysecretkey" >> .env
          echo "DEBUG=True" >> .env
          echo "DATABASE_URL=sqlite:///db.sqlite3" >> .env
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings  # Replace 'myproject' with your project name

      # Run Django migrations (optional)
      - name: Run migrations
        run: |
          python manage.py migrate

      # Run tests
      - name: Run server
        run: |
          python manage.py runserver 0.0.0.0:8000

      # (Optional) Run the Django development server for demo
      # Uncomment below if you want to check if the server starts
      # - name: Run Django server
      #   run: python manage.py runserver 0.0.0.0:8000
