name: CI/CD Pipeline

on:
  push:
    branches:
      - api_chatting  # Trigger this workflow when code is pushed to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Copy repository to the droplet
        run: |
          ssh -o StrictHostKeyChecking=no user@hostname << 'EOF'
          cd /path/to/Django-api
          git checkout api_chatting
          git pull
          EOF

      - name: Build Docker image and deploy
        run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
                echo "Changing directory to /root/Django-api"
                cd /root/Django-api

                echo "Building Docker image: myapp:latest"
                docker build -t myapp:latest .

                echo "Stopping the existing Docker container if it's running"
                docker stop myapp || true

                echo "Removing the Docker container if it exists"
                docker rm myapp || true

                echo "Running a new Docker container from the myapp:latest image"
                docker run -d -p 80:8000 --name myapp myapp:latest

                echo "Deployment completed successfully"
        EOF

